// <auto-generated />
using Discordo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Discordo.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20220526202012_AddActivity")]
    partial class AddActivity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("Discordo.Data.ActivityRecord", b =>
                {
                    b.Property<long>("TimeAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivityName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TimeAdded");

                    b.ToTable("Activities");
                });
#pragma warning restore 612, 618
        }
    }
}
